#该文件中配置红包服务的测试环境配置数据
red:
  remark: '{cipher}AQAsMojPJ0AnYujtKbDD/N3gPVXbJqSw/sWi1LvpAloc9jmt5/dwBXkVWe/q2zHAdVe40VRJk1MVaAQLkQmguJNB8l5sVNXUKTWc8hBEdVRxUUlmKWYZcp8NNWTrINwmGAjvsarotZTb7aWAZcur0pzuCgYxO89zMXKTAPNEr0C1wiBGEL8HDmGQaske7tWk+P3zJ1UMCdB3p5g7itGdIqJBiiAj4pAgu7+4E2BVqqP7f6Hy5UjicuQjmp0bDHe8VdJtf8WC+28n5Ho6N6z7nsDadtBGQDaNaMRhwXUqbX5q9lDgfS3Zus5tIQua1P3U2vsDygYuSpxceXKajKpGkuML3piAwEWANnTDMhQghkX9XlGftczAtlm6BVx620wx0WI='
